clear all
%%
% base = '/Users/hubats01/Desktop/SPT/Us/Diffusion/';
% dirs = {'PAR6/16_04_08_CRT90/16_04_08_crt90',...
%         'PAR6/16_04_08_CRT90/control', ...
%         'PAR6/16_04_09_Early_Embryos/WT_DMSO_NOPERM',...
%         'PAR6/16_04_10_TH411_M9'};
dirs = {'PAR2/16_04_15_NWG0025?', ...
        'PAR2/16_04_18_NWG0025_aPKCRNAi/Analysis', ...
        'PAR2/16_04_20_TH129_PKCRNAi/Analysis', ...
        'PAR2/16_04_22_NWG0025', ...
        'PAR2/16_04_22_TH129', ...
        'PAR2/16_04_23_NWG0025', ...
        'PAR2/16_04_28_TH120'};
%Define logical indices for P0 and P1/dead alive
PAR6_maint = {logical([1, 1, 1, 1, 1, 1, 1]),...
                    logical([1, 1, 1, 1, 1, 1]),...
                    logical([0, 0, 1]),...
                    logical([0, 0, 0, 0, 0])};
PAR6_smooth = {logical([0, 0, 0, 0, 0, 0, 0]),...
                    logical([0, 0, 0, 0, 0, 0]),...
                    logical([0, 0, 0]),...
                    logical([1, 0, 1, 1, 1])};
PAR6_meiotic =      {logical([0, 0, 0, 0, 0, 0, 0]),...
                    logical([0, 0, 0, 0, 0, 0]),...
                    logical([1, 1, 0]),...
                    logical([0, 1, 0, 0, 0])};
PAR6_alive =       {logical([0, 0, 0, 0, 0, 0, 0]),...
                    logical([0, 0, 0, 0, 0, 1]),...
                    logical([0, 0, 0]),...
                    logical([0, 0, 0, 0, 0])};
PAR6_dead =        {logical([1, 1, 1, 1, 1, 1, 1]),...
                    logical([1, 1, 1, 1, 1, 0]),...
                    logical([1, 1, 1]),...
                    logical([1, 1, 1, 1, 1])};
PAR2_maint =       {logical([0, 0, 1, 1, 0, 0, 0, 0]),...
                    logical([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]),...
                    logical([1, 1, 1, 1, 1, 0, 0, 0]),...
                    logical([0, 0, 0, 0, 1, 0, 1, 0]),...
                    logical(1), ...
                    logical([0, 1]),...
                    logical([0, 0, 0, 1, 1, 0])};
PAR2_2cell =       {logical([1, 1, 0, 0, 1, 0, 1, 1]),...
                    logical([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]),...
                    logical([0, 0, 0, 0, 0, 1, 1, 1]),...
                    logical([1, 1, 1, 1, 0, 1, 0, 0]),...
                    logical(0), ...
                    logical([1, 0]),...
                    logical([1, 1, 1, 0, 0, 1])};
PAR2_alive =       {logical([0, 0, 0, 0, 0, 0, 0, 0]),...
                    logical([1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1]),...
                    logical([1, 0, 1, 1, 0, 1, 1, 1]),...
                    logical([1, 0, 0, 1, 1, 0, 1, 0]),...
                    logical(0), ...
                    logical([0, 0]),...
                    logical([1, 1, 1, 1, 0, 1])};
PAR2_dead =       {logical([1, 1, 1, 1, 1, 1, 1, 1]),...
                    logical([0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0]),...
                    logical([0, 1, 0, 0, 1, 0, 0, 0]),...
                    logical([0, 1, 1, 0, 0, 1, 0, 1]),...
                    logical(1), ...
                    logical([1, 1]),...
                    logical([0, 0, 0, 0, 1, 0])};
%%
inds_all = cellfun(@(x, y) x.*y, PAR2_alive, PAR2_2cell, 'UniformOutput', false);
% inds_all = cellfun(@(x, y) x+y, PAR6_alive, PAR6_dead, 'UniformOutput', false);
% inds_all = cellfun(@(x, y) x+y, PAR2_alive, PAR2_dead, 'UniformOutput', false);
% inds_all = PAR6_a; 
% exp_list = [1,2];
% for jjj = 1:length(exp_list)
%     j = exp_list(jjj);
for j = 4:4%length(dirs)
    cd([base, dirs{j}]);
    inds = find(inds_all{j});
%     for i = 1:numel(dir('*.csv'))/2
    clear a
    clear D
    for ii = 1:length(inds)
        i = inds(ii);
        a{i} = csvread(['a', num2str(i), '_600', '.csv']);
        D{i} = csvread(['D', num2str(i), '_600', '.csv']);
    end 
    if exist('a', 'var')
        D_all = cell2mat(D');
        a_all = cell2mat(a');
        D_filt = cellfun(@(x, y) y(x<1.2&x>0.9),a, D, 'UniformOutput', false);
        D_filt_all = cell2mat(D_filt');
        D_means = cellfun(@mean, D_filt, 'UniformOutput', false);
        figure(1); hold on;
        histogram(cell2mat(D'), 0:0.01:0.5, 'Normalization', 'probability', 'DisplayName', dirs{j});
        figure(3); hold on;
        histogram(cell2mat(a'), 0:0.02:1.4, 'Normalization', 'probability', 'DisplayName', dirs{j});
        [n, ~, ~] = histcounts(cell2mat(a'), 0:0.01:1.4, 'Normalization', 'probability');
        figure(4); hold on;
        plot(smooth(n));
        figure(2); hold on;
        plot(a_all, D_all, '.', 'DisplayName', dirs{j});
        numbins = 20;
        D_all = D_all(0<a_all & a_all<1.2);
        a_all = a_all(0<a_all & a_all<1.2);
        [~, edges, bins] = histcounts(a_all,linspace(min(a_all),max(a_all), numbins));
        centers = edges+0.0125;
        centers = centers(1:end-1);
        fs = full(sparse(1:length(a_all),bins,D_all));
        fs(fs==0) = NaN;
        m = nanmean(fs);
        plot(centers, m, 'b', 'LineWidth', 3, 'DisplayName', dirs{j});
        axis([0, 1.2, 0, 0.5]);
    end
end
figure(1)
legend(gca, 'show');
figure(2)
legend(gca,'show')
%%
plot(cell2mat(a_con),cell2mat(D_con), '.', 'MarkerSize', 8); hold on;
plot(cell2mat(a_crt),cell2mat(D_crt), '.', 'MarkerSize', 8);
xlabel('Anomalous Diffusion exponent', 'FontSize', 16);
ylabel('D (um^2/s)', 'FontSize', 16);
%%
figure(1); hold on;
for i = 1:6
    plot(a{i}, D{i}, 'b.', 'MarkerSize', 8);
end
for i = 7:11
    plot(a{i}, D{i}, 'r.', 'MarkerSize', 8);
end
%%
histogram(cell2mat(between_09_12_con)','Normalization','pdf'); hold on;
histogram(cell2mat(between_09_12_crt)','Normalization','pdf')
%%
histogram([D_con{:}],'Normalization','pdf'); hold on;
histogram([D_crt{:}]','Normalization','pdf')