%%  When getting new data make sure to put things in different folders for
%   easier analysis
clear all
%%
base = '/Users/hubatsl/Desktop/SPT/Us/Diffusion/';
dirs = {'PAR6/16_04_08_CRT90/16_04_08_crt90',...
        'PAR6/16_04_08_CRT90/control', ...
        'PAR6/16_04_09_Early_Embryos/WT_DMSO_NOPERM',...
        'PAR6/16_04_10_TH411_M9',...
        'PAR6/Feb_2016'};
% dirs = {'PAR2/16_04_15_NWG0025?', ...
%         'PAR2/16_04_18_NWG0025_aPKCRNAi/Analysis', ...
%         'PAR2/16_04_20_TH129_PKCRNAi/Analysis', ...
%         'PAR2/16_04_22_NWG0025', ...
%         'PAR2/16_04_22_TH129', ...
%         'PAR2/16_04_23_NWG0025', ...
%         'PAR2/16_04_28_TH120', ...
%         'PAR2/16_05_06_TH120'};
%Define logical indices for P0 and P1/dead alive
PAR6_maint =   {logical([1, 1, 1, 1, 1, 1, 1]),...
                logical([1, 1, 1, 1, 1, 1]),...
                logical([0, 0, 1]),...
                logical([0, 0, 0, 0, 0]),...
                logical([1, 1, 1, 1, 1])};
PAR6_smooth =  {logical([0, 0, 0, 0, 0, 0, 0]),...
                logical([0, 0, 0, 0, 0, 0]),...
                logical([0, 0, 0]),...
                logical([1, 0, 1, 1, 1]),...
                logical([0, 0, 0, 0, 0])};
PAR6_meiotic = {logical([0, 0, 0, 0, 0, 0, 0]),...
                logical([0, 0, 0, 0, 0, 0]),...
                logical([1, 1, 0]),...
                logical([0, 1, 0, 0, 0]),...
                logical([0, 0, 0, 0, 0])};
PAR6_alive =   {logical([0, 0, 0, 0, 0, 0, 0]),...
                logical([0, 0, 0, 0, 0, 1]),...
                logical([0, 0, 0]),...
                logical([0, 0, 0, 0, 0]),...
                logical([0, 0, 0, 0, 0])};
PAR6_dead =    {logical([1, 1, 1, 1, 1, 1, 1]),...
                logical([1, 1, 1, 1, 1, 0]),...
                logical([1, 1, 1]),...
                logical([1, 1, 1, 1, 1]),...
                logical([1, 1, 1, 1, 1])};
PAR2_maint =       {logical([0, 0, 1, 1, 0, 0, 0, 0]),...
                    logical([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]),...
                    logical([1, 1, 1, 1, 1, 0, 0, 0]),...
                    logical([0, 0, 0, 0, 1, 0, 1, 0]),...
                    logical(1), ...
                    logical([0, 1]),...
                    logical([0, 0, 0, 1, 1, 0]), ...
                    logical([1, 0, 0, 1, 1, 1, 1, 0])};
PAR2_2cell =       {logical([1, 1, 0, 0, 1, 0, 1, 1]),...
                    logical([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]),...
                    logical([0, 0, 0, 0, 0, 1, 1, 1]),...
                    logical([1, 1, 1, 1, 0, 1, 0, 0]),...
                    logical(0), ...
                    logical([1, 0]),...
                    logical([1, 1, 1, 0, 0, 1]), ...
                    logical([0, 0, 1, 0, 0, 0, 0, 1])};
PAR2_alive =       {logical([0, 0, 0, 0, 0, 0, 0, 0]),...
                    logical([1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1]),...
                    logical([1, 0, 1, 1, 0, 1, 1, 1]),...
                    logical([1, 0, 0, 1, 1, 0, 1, 0]),...
                    logical(0), ...
                    logical([0, 0]),...
                    logical([1, 1, 1, 1, 0, 1]), ...
                    logical([1, 0, 1, 1, 1, 1, 1, 1])};
PAR2_dead =       {logical([1, 1, 1, 1, 1, 1, 1, 1]),...
                    logical([0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0]),...
                    logical([0, 1, 0, 0, 1, 0, 0, 0]),...
                    logical([0, 1, 1, 0, 0, 1, 0, 1]),...
                    logical(1), ...
                    logical([1, 1]),...
                    logical([0, 0, 0, 0, 1, 0]), ...
                    logical([0, 1, 0, 0, 0, 0, 0, 0])};
PAR2_Schroedinger = cellfun(@plus, PAR2_dead, PAR2_alive, 'UniformOutput', false);
PAR6_Schroedinger = cellfun(@plus, PAR6_dead, PAR6_alive, 'UniformOutput', false);
PAR6_smooth_meiotic = cellfun(@plus, PAR6_meiotic, PAR6_smooth, 'UniformOutput', false);
%% THIS IS SECTION I
% inds_all = cellfun(@(x, y) x.*y, PAR2_Schroedinger, PAR2_maint, 'UniformOutput', false);
inds_all = cellfun(@(x, y) x.*y, PAR6_Schroedinger, PAR6_smooth_meiotic, 'UniformOutput', false);
D_all = cell(1, length(dirs));
a_all = D_all;
for j = 1:length(dirs)
    cd([base, dirs{j}]);
    inds = find(inds_all{j});
    a = cell(1, length(inds));
    D = cell(1, length(inds));
    for ii = 1:length(inds)
        i = inds(ii);
        try 
            a{i} = csvread(['a', num2str(i), '_600', '.csv']);
            D{i} = csvread(['D', num2str(i), '_600', '.csv']);
        catch
            a{i} = csvread(['a', num2str(i), '_550', '.csv']);
            D{i} = csvread(['D', num2str(i), '_550', '.csv']);
        end   
    end 
    if ~isempty(a) %Checking, whether folder contained any files that were relevant
        %Plotting histogram of a and D for all data together
        D_all{j} = cell2mat(D');
        a_all{j} = cell2mat(a');
        D_filt = cellfun(@(x, y) y(x<1.2&x>0.9),a, D, 'UniformOutput', false);
        D_filt_all = cell2mat(D_filt');
        D_means = cellfun(@nanmean, D_filt, 'UniformOutput', false);
        figure(1); hold on;
        histogram(cell2mat(D'), 0:0.01:0.5, 'Normalization', 'probability', 'DisplayName', dirs{j});
        figure(3); hold on;
        histogram(cell2mat(a'), 0:0.02:1.4, 'Normalization', 'probability', 'DisplayName', dirs{j});
        [n, ~, ~] = histcounts(cell2mat(a'), 0:0.01:1.4, 'Normalization', 'probability');
        figure(4); hold on;
        plot(smooth(n));
        figure(2); hold on;
        plot(a_all{j}, D_all{j}, '.', 'DisplayName', dirs{j});
        numbins = 20;
        D_all{j} = D_all{j}(0.9<a_all{j} & a_all{j}<1.2);
        a_all{j} = a_all{j}(0.9<a_all{j} & a_all{j}<1.2);
        [~, edges, bins] = histcounts(a_all{j},linspace(min(a_all{j}),max(a_all{j}), numbins));
        centers = edges+0.0125;
        centers = centers(1:end-1);
        fs = full(sparse(1:length(a_all{j}),bins,D_all{j}));
        fs(fs==0) = NaN;
        m = nanmean(fs);
        plot(centers, m, 'm', 'LineWidth', 3, 'DisplayName', dirs{j});
        axis([0, 1.2, 0, 0.5]);
        Dm{j} = mean(D_all{j});
        am{j} = mean(a_all{j});
        Dstd{j} = std(D_all{j});
    end
end
figure(1)
legend(gca, 'show');
figure(2)
legend(gca,'show')

%% PAR-6: Run section I with below inds_all to get PAR-6 diffusivities
%%%%Running with inds_all = cellfun(@(x, y) x.*y, PAR6_Schroedinger, PAR6_maint, 'UniformOutput', false);
%D_crt = D_all{1}'; 
%D_crt_control = D_all{2}';
%D_wt = [D_all{3}', D_all{4}', D_all{5}'];
%%%%Running with inds_all = cellfun(@(x, y) x.*y, PAR6_Schroedinger, PAR6_smooth_meiotic, 'UniformOutput', false);

%%
D_crt = 0.1193;
D_crt_s = 0.0559;
D_crt_control = 0.1563;
D_crt_control_s = 0.0697;
D_wt = 0.1430; %Does not include crt_control
D_wt_s = 0.0846;
D_wt_meiotic_smooth = 0.1028; % n = 5
D_wt_meiotic_smooth_s = 0.0614;
Ds = [D_crt, D_crt_control, D_wt, D_wt_meiotic_smooth];
Dstds = [D_crt_s, D_crt_control_s, D_wt_s, D_wt_meiotic_smooth_s];
figure;
bar(Ds); hold on;
errorbar(1:length(Ds),Ds,Dstds,'.');
specs = {'CRT', 'CRT Con','WT (no CRT Con)', 'Early'}; 
set(gca,'xtick',[1 2 3 4], 'XTickLabel',specs, 'FontSize', 18);
ylabel('D [$\frac{\mu ^2}{s}$]', 'Interpreter', 'Latex', 'FontSize', 24);

%% PAR-2: Run section I with below inds_all to get PAR-2 diffusivity for 
%  either PAR2_maint or PAR2_2cell, get mean values and their std.
%inds_all = cellfun(@(x, y) x.*y, PAR2_Schroedinger, PAR2_maint, 'UniformOutput', false);
D_25 = [D_all{1}',D_all{4}',D_all{6}']; %Get NWG0025
D_wt = [D_all{7}',D_all{5}',D_all{8}']; %Get wt (TH129 or TH120)
%% Above was done for PAR2_Schroedinger, PAR2_2cell/PAR2_maint, giving the following:
D_25_maint = 0.1383;
D_25_2cell = 0.1159;
D_wt_maint = 0.1276;
D_wt_2cell = 0.1292;
D_25_maint_s = 0.0709;
D_25_2cell_s = 0.0576;
D_wt_maint_s = 0.0584;
D_wt_2cell_s = 0.0660;
Ds = [D_25_maint, D_wt_maint, D_25_2cell, D_wt_2cell];
Dstds = [D_25_maint_s, D_wt_maint_s, D_25_2cell_s, D_wt_2cell_s];

figure
bar(Ds); hold on;
errorbar(1:length(Ds),Ds,Dstds,'.');
specs = {'Big-1 P0', 'WT P0','Big-1 P1', 'WT P1'}; 
set(gca,'xtick',[1 2 3 4], 'XTickLabel',specs, 'FontSize', 18);
ylabel('D [$\frac{\mu ^2}{s}$]', 'Interpreter', 'Latex', 'FontSize', 24);
